name: CI/CD Deploy

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE_FRONTEND: jay1261/howtoeat-front

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: make url.js
        run: |
          echo 'window.DOMAIN_URL="http://localhost:8080"' > public/user/js/utils/url.js
        shell: bash

      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE_FRONTEND }}:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker-compose pull frontend
            docker-compose stop frontend
            docker-compose rm -f frontend
            docker-compose up -d frontend
            docker image prune -f
